# Generated by Django 5.2.17 on 2026-09-09 06:52

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pandals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('curated_tour', 'Curated tour'), ('puja_in_your_name', 'Puja in your name'), ('special_assistance', 'Special assistance'), ('aarti_slot', 'Aarti slot'), ('generic', 'Priced service')], default='generic', max_length=24)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_paise', models.BigIntegerField()),
                ('max_per_booking', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pandals.pandal')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceDayCapacity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'service day capacities',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ServiceCapacityHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_holds', to='orders.order')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='services.servicedaycapacity')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('held', 'Held, awaiting payment'), ('confirmed', 'Confirmed'), ('expired', 'Hold expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='held', max_length=12)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_booking', to='orders.orderline')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
                ('hold', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='services.servicecapacityhold')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.servicedaycapacity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('pandal', 'slug'), name='uniq_service_slug_per_pandal'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_paise__gte', 0)), name='service_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='servicedaycapacity',
            constraint=models.UniqueConstraint(fields=('service', 'date'), name='uniq_service_day'),
        ),
        migrations.AddConstraint(
            model_name='servicedaycapacity',
            constraint=models.CheckConstraint(condition=models.Q(('issued_count__lte', models.F('capacity'))), name='service_day_issued_within_capacity'),
        ),
        migrations.AddIndex(
            model_name='servicecapacityhold',
            index=models.Index(fields=['day', 'expires_at'], name='services_se_day_id_a4acae_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['service', 'status'], name='services_se_service_c200ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicebooking',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='service_booking_quantity_positive'),
        ),
    ]
