# Generated by Django 5.2.17 on 2026-09-09 10:25

import apps.common.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_capacity',
            field=models.BooleanField(default=True, help_text='Off for something with no daily limit, like a postal delivery.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(blank=True, default='', help_text="A label for grouping, e.g. 'Darshan' or 'Prasad'. Optional.", max_length=40),
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('phone', 'Mobile number'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('select', 'Choose one'), ('checkbox', 'Yes or no')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.service')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('service', 'key'), name='uniq_field_key_per_service')],
            },
        ),
    ]
