# Generated by Django 5.2.17 on 2026-09-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_materialise_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.servicedaycapacity'),
        ),
    ]
