# Generated by Django 5.2.17 on 2026-09-09 06:52

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pandals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PandalLiveStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('estimated_wait_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crowd_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=8)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('pandal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_status', to='pandals.pandal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pandal live statuses',
                'ordering': ('pandal__name',),
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('returned', 'Returned')], default='lost', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to='pandals.pandal')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_item_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['pandal', 'status', '-created_at'], name='ops_lostite_pandal__44bc53_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General inquiry'), ('donation', 'Donation'), ('service', 'Service booking'), ('feedback', 'Feedback & suggestion')], default='general', max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pandal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='pandals.pandal')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='ops_support_status_8cfedf_idx')],
            },
        ),
    ]
