# Generated by Django 5.2.17 on 2026-09-09 07:56

import apps.common.uuid7
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pandals', '0002_gate_volunteer_gate_uniq_gate_name_per_pandal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingPlacement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price_per_week_paise', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sponsorship.organisation')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PassRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('granted', 'Granted'), ('refused', 'Refused')], default='open', max_length=8)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_requests', to='sponsorship.organisation')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_requests', to='pandals.pandal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('granted', models.PositiveIntegerField(default=0)),
                ('transferred_out', models.PositiveIntegerField(default=0)),
                ('issued', models.PositiveIntegerField(default=0)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='sponsorship.organisation')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='pandals.pandal')),
                ('parent_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_pools', to='sponsorship.pool')),
            ],
            options={
                'ordering': ('organisation__name',),
            },
        ),
        migrations.CreateModel(
            name='PoolTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_pass_paise', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('from_pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='sponsorship.pool')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_transfers', to='orders.order')),
                ('to_pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='sponsorship.pool')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('value_paise', models.BigIntegerField()),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('banner_placements', models.PositiveSmallIntegerField(default=0)),
                ('benefits', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_packages', to='pandals.pandal')),
            ],
            options={
                'ordering': ('-value_paise', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PoolAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('pass_count', models.PositiveIntegerField()),
                ('value_paise', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sponsorship.organisation')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_allocations', to='pandals.pandal')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='sponsorship.pool')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='sponsorship.sponsorshippackage')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BrandingCreative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('target_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_paise', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branding_creatives', to='pandals.pandal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='sponsorship.brandingplacement')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='sponsorship.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['pandal', 'placement', 'status'], name='sponsorship_pandal__cefbdc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='creative_dates_ordered')],
            },
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('organisation', 'pandal'), name='uniq_pool_per_org_per_pandal'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.CheckConstraint(condition=models.Q(('transferred_out__lte', django.db.models.expressions.CombinedExpression(models.F('granted'), '-', models.F('issued')))), name='pool_outflow_within_grant'),
        ),
        migrations.AddConstraint(
            model_name='pooltransfer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transfer_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='sponsorshippackage',
            constraint=models.UniqueConstraint(fields=('pandal', 'slug'), name='uniq_package_slug_per_pandal'),
        ),
        migrations.AddConstraint(
            model_name='sponsorshippackage',
            constraint=models.CheckConstraint(condition=models.Q(('value_paise__gte', 0)), name='package_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='poolallocation',
            index=models.Index(fields=['organisation', 'status'], name='sponsorship_organis_c13284_idx'),
        ),
        migrations.AddConstraint(
            model_name='poolallocation',
            constraint=models.CheckConstraint(condition=models.Q(('pass_count__gt', 0)), name='allocation_count_positive'),
        ),
    ]
