# Generated by Django 5.2.17 on 2026-09-09 07:34

import apps.common.uuid7
import apps.passes.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pandals', '0002_gate_volunteer_gate_uniq_gate_name_per_pandal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PandalDayCapacity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_capacities', to='pandals.pandal')),
            ],
            options={
                'verbose_name_plural': 'pandal day capacities',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='PandalCapacityHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pandal_holds', to='orders.order')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='passes.pandaldaycapacity')),
            ],
        ),
        migrations.CreateModel(
            name='PassCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_categories', to='pandals.pandal')),
            ],
            options={
                'verbose_name_plural': 'pass categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('city', 'City')], max_length=12)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('pass_code', models.CharField(default=apps.passes.models.generate_pass_code, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Fully used'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='active', max_length=12)),
                ('source', models.CharField(choices=[('retail', 'Bought by the visitor'), ('sponsor_pool', "Issued from a sponsor's pool"), ('complimentary', 'Issued without payment')], default='retail', max_length=16)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_issued', to='orders.orderline')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='passes.passcategory')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PassConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('city', 'City')], max_length=12)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('price_paise', models.BigIntegerField()),
                ('max_party_size', models.PositiveSmallIntegerField(default=1)),
                ('slot_cap', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='passes.passcategory')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_configs', to='pandals.pandal')),
            ],
            options={
                'ordering': ('from_date', 'from_time'),
            },
        ),
        migrations.CreateModel(
            name='PassConfigChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=16)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('remaining_count', models.PositiveIntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='passes.passconfig')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_config_changes', to='pandals.pandal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PassLeg',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('slot_from', models.TimeField(blank=True, null=True)),
                ('slot_to', models.TimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('visited', 'Visited'), ('void', 'Void')], default='pending', max_length=8)),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('admitted_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='pandals.gate')),
                ('capacity_hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='passes.pandalcapacityhold')),
                ('issued_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='passes.pass')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pass_legs', to='pandals.pandal')),
            ],
            options={
                'ordering': ('visit_date', 'slot_from'),
            },
        ),
        migrations.CreateModel(
            name='LegSecret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(help_text='Base64 of 64 random bytes', max_length=88)),
                ('provisioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('leg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secret', to='passes.passleg')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=80)),
                ('presented_code', models.CharField(blank=True, max_length=64)),
                ('result', models.CharField(choices=[('admitted', 'Admitted'), ('expired', 'Code expired'), ('duplicate', 'Already used'), ('invalid', 'Not a valid code'), ('manual_override', 'Admitted by exception')], max_length=16)),
                ('scanned_at', models.DateTimeField(help_text="The gate device's clock")),
                ('received_at', models.DateTimeField(blank=True, help_text='When it reached us', null=True)),
                ('override_reason', models.CharField(blank=True, max_length=255)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='pandals.gate')),
                ('leg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='passes.passleg')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='pandals.volunteer')),
            ],
            options={
                'ordering': ('-scanned_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='pandaldaycapacity',
            constraint=models.UniqueConstraint(fields=('pandal', 'date'), name='uniq_pandal_day'),
        ),
        migrations.AddConstraint(
            model_name='pandaldaycapacity',
            constraint=models.CheckConstraint(condition=models.Q(('issued_count__lte', models.F('capacity'))), name='pandal_day_issued_within_capacity'),
        ),
        migrations.AddIndex(
            model_name='pandalcapacityhold',
            index=models.Index(fields=['day', 'expires_at'], name='passes_pand_day_id_1c9e37_idx'),
        ),
        migrations.AddConstraint(
            model_name='passcategory',
            constraint=models.UniqueConstraint(fields=('pandal', 'slug'), name='uniq_category_slug_per_pandal'),
        ),
        migrations.AddIndex(
            model_name='pass',
            index=models.Index(fields=['holder', 'status'], name='passes_pass_holder__7bdbd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='pass',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gt', 0)), name='pass_party_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='pass',
            constraint=models.CheckConstraint(condition=models.Q(('product', 'group'), ('party_size', 1), _connector='OR'), name='only_group_pass_covers_many'),
        ),
        migrations.AddConstraint(
            model_name='passconfig',
            constraint=models.CheckConstraint(condition=models.Q(('price_paise__gte', 0)), name='pass_config_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='passconfig',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='pass_config_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='passconfig',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product', 'city'), _negated=True), ('from_time__isnull', True), _connector='OR'), name='city_pass_has_no_time'),
        ),
        migrations.AddIndex(
            model_name='passleg',
            index=models.Index(fields=['pandal', 'visit_date', 'state'], name='passes_pass_pandal__e768b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='passleg',
            constraint=models.UniqueConstraint(fields=('issued_pass', 'pandal'), name='uniq_leg_per_pandal'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['gate', '-scanned_at'], name='passes_scan_gate_id_a726eb_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['result', '-scanned_at'], name='passes_scan_result_10d4ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanevent',
            constraint=models.UniqueConstraint(condition=models.Q(('result__in', ['admitted', 'manual_override'])), fields=('leg',), name='one_admission_per_leg'),
        ),
    ]
