# Generated by Django 5.2.17 on 2026-09-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes', to='sponsorship.pool'),
        ),
    ]
