# Generated by Django 5.2.17 on 2026-09-09 06:52

import apps.common.uuid7
import apps.pandals.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pandal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(help_text='Also the subdomain: <slug>.edurgapuja.app', max_length=63, unique=True, validators=[apps.pandals.validators.validate_subdomain])),
                ('custom_domain', models.CharField(blank=True, help_text='Unused in v1 (FR-249)', max_length=253, null=True, unique=True)),
                ('committee_name', models.CharField(blank=True, max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('theme_name', models.CharField(blank=True, max_length=120)),
                ('theme_name_local', models.CharField(blank=True, help_text='The theme in Bengali, e.g. প্রথা', max_length=120)),
                ('sells_passes', models.BooleanField(default=False)),
                ('accepts_donations', models.BooleanField(default=True)),
                ('offers_services', models.BooleanField(default=False)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('opens_on', models.DateField(blank=True, null=True)),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='pandals/og/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pandals', to='geo.city')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pandals', to='geo.locality')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('marquee', 'Marquee'), ('about', 'About'), ('donor_pass', 'Donor Pass'), ('donate', 'Donate'), ('services', 'Value-Added Services'), ('visit', 'Plan Your Visit'), ('closing_cta', 'Closing call to action'), ('footer', 'Footer')], max_length=16)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali'), ('hi', 'Hindi')], default='en', max_length=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pandals.pandal')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PandalBrand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('primary_colour', models.CharField(default='#B45F1E', max_length=9)),
                ('accent_colour', models.CharField(default='#E0A66A', max_length=9)),
                ('surface_colour', models.CharField(default='#FBF3E8', max_length=9)),
                ('ink_colour', models.CharField(default='#3A1D0C', max_length=9)),
                ('display_font', models.CharField(blank=True, max_length=80)),
                ('body_font', models.CharField(blank=True, max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pandals/logo/')),
                ('mark', models.ImageField(blank=True, null=True, upload_to='pandals/mark/')),
                ('pandal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='pandals.pandal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PandalDomainAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=253, unique=True)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_aliases', to='pandals.pandal')),
            ],
            options={
                'verbose_name_plural': 'pandal domain aliases',
            },
        ),
        migrations.CreateModel(
            name='VisitFact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_facts', to='pandals.pandal')),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddIndex(
            model_name='pandal',
            index=models.Index(fields=['city', 'publication_status'], name='pandals_pan_city_id_71e9d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageblock',
            constraint=models.UniqueConstraint(fields=('pandal', 'kind', 'language'), name='uniq_block_per_pandal_kind_language'),
        ),
    ]
