# Generated by Django 5.2.17 on 2026-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0002_gate_volunteer_gate_uniq_gate_name_per_pandal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='kind',
            field=models.CharField(choices=[('hero', 'Hero'), ('marquee', 'Marquee'), ('about', 'About'), ('passes', 'Passes'), ('donate', 'Donate'), ('services', 'Value-Added Services'), ('visit', 'Plan Your Visit'), ('closing_cta', 'Closing call to action'), ('footer', 'Footer')], max_length=16),
        ),
    ]
