# Generated by Django 5.2.17 on 2026-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0003_alter_pageblock_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pandalbrand',
            name='accent_colour',
            field=models.CharField(default='#D4AF37', max_length=9),
        ),
        migrations.AlterField(
            model_name='pandalbrand',
            name='ink_colour',
            field=models.CharField(default='#241A18', max_length=9),
        ),
        migrations.AlterField(
            model_name='pandalbrand',
            name='primary_colour',
            field=models.CharField(default='#7B0D1E', max_length=9),
        ),
        migrations.AlterField(
            model_name='pandalbrand',
            name='surface_colour',
            field=models.CharField(default='#FAF6EE', max_length=9),
        ),
    ]
