# Generated by Django 5.2.17 on 2026-09-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandals', '0004_alter_pandalbrand_accent_colour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('user__first_name', 'user__phone')},
        ),
    ]
