# Generated by Django 5.2.17 on 2026-09-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pandals', '0002_gate_volunteer_gate_uniq_gate_name_per_pandal_and_more'),
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminmembership',
            name='uniq_membership_scope',
        ),
        migrations.AddField(
            model_name='adminmembership',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sponsorship.organisation'),
        ),
        migrations.AlterField(
            model_name='adminmembership',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('pandal_admin', 'Pandal Admin'), ('sponsor_admin', 'Sponsor Admin'), ('sub_sponsor_admin', 'Sub-Sponsor Admin')], max_length=24),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('pandal_admin', 'Pandal Admin'), ('sponsor_admin', 'Sponsor Admin'), ('sub_sponsor_admin', 'Sub-Sponsor Admin')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='adminmembership',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'pandal', 'organisation'), name='uniq_membership_scope'),
        ),
    ]
