# Generated by Django 5.2.17 on 2026-09-09 17:25

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pan', 'PAN')], default='pan', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Awaiting the provider'), ('verified', 'Verified'), ('failed', 'Not verified'), ('error', 'Could not be checked')], default='pending', max_length=8)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('name_on_record', models.CharField(blank=True, max_length=140)),
                ('name_submitted', models.CharField(blank=True, max_length=140)),
                ('provider', models.CharField(default='sandbox', max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='kyc_kycchec_user_id_926f72_idx')],
            },
        ),
    ]
