# Generated by Django 5.2.17 on 2026-09-09 06:52

import apps.common.uuid7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending with provider'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed')], default='created', max_length=12)),
                ('method', models.CharField(blank=True, choices=[('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet'), ('netbanking', 'Net banking')], max_length=12)),
                ('amount_paise', models.BigIntegerField()),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(default='razorpay', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='razorpay', max_length=20)),
                ('event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('signature_verified', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='payments.paymentorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='requested', max_length=12)),
                ('provider_refund_id', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_71e312_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_provider_event'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='refund_amount_positive'),
        ),
    ]
