# Generated by Django 5.2.17 on 2026-09-09 06:52

import apps.common.uuid7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pandals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('suggested_amount_paise', models.BigIntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=140)),
                ('token', models.CharField(editable=False, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_links', to='pandals.pandal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DonationOffering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_offerings', to='pandals.pandal')),
            ],
            options={
                'ordering': ('sort_order', 'amount_paise'),
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=apps.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('message', models.CharField(blank=True, max_length=280)),
                ('amount_paise', models.BigIntegerField()),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('order_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='orders.orderline')),
                ('pandal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='pandals.pandal')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationlink')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.donationoffering')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='donationoffering',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='offering_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['pandal', '-created_at'], name='donations_d_pandal__75e009_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='donation_amount_positive'),
        ),
    ]
