# Generated by Django 5.2.17 on 2026-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
