# Generated by Django 5.2.17 on 2026-09-09 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_received_at'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='kyc_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='kyc.kyccheck'),
        ),
    ]
